import { StyleSheet } from 'react-native';
import { FONTS } from './global';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  blueSection: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 225,
    backgroundColor: '#0000FF',
  },
  backButton: {
    position: 'absolute',
    top: 48,
    left: 16,
    width: 40,
    height: 40,
    backgroundColor: 'transparent',
    borderColor: '#FAFAFA',
    borderWidth: 1,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  welcomeText: {
    position: 'absolute',
    top: 110,
    left: 20,
    right: 20,
    color: '#FFFFFF',
    fontSize: 42,
    fontFamily: FONTS.bold,
    lineHeight: 50,
  },
  tabsContainer: {
    position: 'absolute',
    top: 240,
    left: 30,
    right: 30,
  },
  formContainer: {
    position: 'absolute',
    top: 290,
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: 20,
  },
  label: {
    fontSize: 16,
    fontFamily: FONTS.semibold,
    color: '#000000',
    marginBottom: 8,
    marginTop: 14,
  },
  input: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D0D0D0',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 10,
    fontSize: 16,
    fontFamily: FONTS.regular,
    color: '#000000',
  },
  inputFocused: {
    borderColor: '#A3A3A3',
    borderWidth: 2.2,
  },
  passwordContainer: {
    position: 'relative',
    flexDirection: 'row',
    alignItems: 'center',
  },
  passwordContainerFocused: {
    borderColor: '#0000FF',
    borderWidth: 2,
    borderRadius: 12,
  },
  passwordInput: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D0D0D0',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 10,
    paddingRight: 50,
    fontSize: 16,
    fontFamily: FONTS.regular,
    color: '#000000',
  },
  eyeIcon: {
    position: 'absolute',
    right: 16,
  },
  registerButton: {
    backgroundColor: '#0000FF',
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    marginTop: 24,
  },
  registerButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontFamily: FONTS.semibold,
  },
  orText: {
    textAlign: 'center',
    fontSize: 16,
    fontFamily: FONTS.semibold,
    color: '#000000',
    marginVertical: 16,
  },
  kingschatButton: {
    backgroundColor: '#1E90FF',
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    marginBottom: 40,
  },
  kingschatIcon: {
    width: 26,
    height: 26,
    marginLeft: 8,
  },
  kingschatButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontFamily: FONTS.semibold,
  },
  forgotPasswordContainer: {
    alignSelf: 'flex-start',
    marginTop: 8,
  },
  forgotPasswordText: {
    color: '#666',
    fontSize: 14,
    fontFamily: FONTS.regular,
  },
});
