import { StyleSheet } from 'react-native';
import { FONTS } from './global';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#FFFFFF',
  },
  blueSection: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 320,
    backgroundColor: '#0000FF',
  },
  backButton: {
    position: 'absolute',
    top: 48,
    left: 16,
    width: 56,
    height: 53,
    backgroundColor: 'transparent',
    borderColor: '#FAFAFA',
    borderWidth: 1,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerText: {
    position: 'absolute',
    top: 180,
    left: 20,
    right: 20,
    color: '#FFFFFF',
    fontSize: 42,
    fontFamily: FONTS.bold,
    lineHeight: 50,
  },
  contentContainer: {
    position: 'absolute',
    top: 360,
    left: 0,
    right: 0,
    paddingHorizontal: 20,
    alignItems: 'center',
  },
  instructionText: {
    fontSize: 18,
    fontFamily: FONTS.regular,
    color: '#000000',
    textAlign: 'center',
    marginBottom: 8,
  },
  emailText: {
    fontSize: 18,
    fontFamily: FONTS.semibold,
    color: '#000000',
    textAlign: 'center',
    marginBottom: 40,
  },
  codeContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 60,
  },
  codeGroup: {
    flexDirection: 'row',
    gap: 12,
  },
  codeSeparator: {
    width: 20,
  },
  codeInput: {
    width: 56,
    height: 64,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#D0D0D0',
    borderRadius: 12,
    fontSize: 24,
    fontFamily: FONTS.semibold,
    color: '#000000',
    textAlign: 'center',
  },
  verifyButton: {
    width: '100%',
    backgroundColor: '#0000FF',
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center',
    position: 'absolute',
    bottom: -600,
    left: 20,
    right: 20,
  },
  verifyButtonText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontFamily: FONTS.semibold,
  },
});
